// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.mccartycarclub.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ChatHostPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class Contact (
  val userName: String? = null,
  val phoneNumber: String? = null,
  val userId: String? = null,
  val avatarUri: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Contact {
      val userName = pigeonVar_list[0] as String?
      val phoneNumber = pigeonVar_list[1] as String?
      val userId = pigeonVar_list[2] as String?
      val avatarUri = pigeonVar_list[3] as String?
      return Contact(userName, phoneNumber, userId, avatarUri)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      userName,
      phoneNumber,
      userId,
      avatarUri,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Contact) {
      return false
    }
    if (this === other) {
      return true
    }
    return ChatHostPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Group (
  val groudId: String? = null,
  val groupName: String? = null,
  val groupAvatarUri: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Group {
      val groudId = pigeonVar_list[0] as String?
      val groupName = pigeonVar_list[1] as String?
      val groupAvatarUri = pigeonVar_list[2] as String?
      return Group(groudId, groupName, groupAvatarUri)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      groudId,
      groupName,
      groupAvatarUri,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Group) {
      return false
    }
    if (this === other) {
      return true
    }
    return ChatHostPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Chat (
  val chatId: String? = null,
  val userName: String? = null,
  val avatarUri: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Chat {
      val chatId = pigeonVar_list[0] as String?
      val userName = pigeonVar_list[1] as String?
      val avatarUri = pigeonVar_list[2] as String?
      return Chat(chatId, userName, avatarUri)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      chatId,
      userName,
      avatarUri,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Chat) {
      return false
    }
    if (this === other) {
      return true
    }
    return ChatHostPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Message (
  val messageId: String? = null,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Message {
      val messageId = pigeonVar_list[0] as String?
      val message = pigeonVar_list[1] as String?
      return Message(messageId, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      messageId,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Message) {
      return false
    }
    if (this === other) {
      return true
    }
    return ChatHostPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class ChatHostPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Contact.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Group.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Chat.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Message.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is Contact -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is Group -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is Chat -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is Message -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CerqaHostApi {
  fun fetchChats(callback: (Result<List<Chat>>) -> Unit)
  fun fetchDirectConversation(receiverUserId: String, callback: (Result<List<Message>>) -> Unit)
  fun createMessage()
  fun deleteMessage()
  fun createChat(receiverUserId: String)
  fun deleteChat()
  fun doesGroupNameExist(groupName: String): Boolean
  fun fetchGroupChats(callback: (Result<List<Group>>) -> Unit)
  fun fetchGroupConversation()
  fun deleteGroupMessage()
  fun fetchGroupMessage()
  fun createGroupMessage()
  fun createGroup(groupName: String)
  fun deleteGroup()
  fun fetchContacts(callback: (Result<List<Contact>>) -> Unit)

  companion object {
    /** The codec used by CerqaHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ChatHostPigeonCodec()
    }
    /** Sets up an instance of `CerqaHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CerqaHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cerqa_flutter_module.CerqaHostApi.fetchChats$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.fetchChats{ result: Result<List<Chat>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ChatHostPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ChatHostPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cerqa_flutter_module.CerqaHostApi.fetchDirectConversation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val receiverUserIdArg = args[0] as String
            api.fetchDirectConversation(receiverUserIdArg) { result: Result<List<Message>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ChatHostPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ChatHostPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cerqa_flutter_module.CerqaHostApi.createMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.createMessage()
              listOf(null)
            } catch (exception: Throwable) {
              ChatHostPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cerqa_flutter_module.CerqaHostApi.deleteMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.deleteMessage()
              listOf(null)
            } catch (exception: Throwable) {
              ChatHostPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cerqa_flutter_module.CerqaHostApi.createChat$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val receiverUserIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.createChat(receiverUserIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              ChatHostPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cerqa_flutter_module.CerqaHostApi.deleteChat$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.deleteChat()
              listOf(null)
            } catch (exception: Throwable) {
              ChatHostPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cerqa_flutter_module.CerqaHostApi.doesGroupNameExist$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val groupNameArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.doesGroupNameExist(groupNameArg))
            } catch (exception: Throwable) {
              ChatHostPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cerqa_flutter_module.CerqaHostApi.fetchGroupChats$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.fetchGroupChats{ result: Result<List<Group>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ChatHostPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ChatHostPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cerqa_flutter_module.CerqaHostApi.fetchGroupConversation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.fetchGroupConversation()
              listOf(null)
            } catch (exception: Throwable) {
              ChatHostPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cerqa_flutter_module.CerqaHostApi.deleteGroupMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.deleteGroupMessage()
              listOf(null)
            } catch (exception: Throwable) {
              ChatHostPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cerqa_flutter_module.CerqaHostApi.fetchGroupMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.fetchGroupMessage()
              listOf(null)
            } catch (exception: Throwable) {
              ChatHostPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cerqa_flutter_module.CerqaHostApi.createGroupMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.createGroupMessage()
              listOf(null)
            } catch (exception: Throwable) {
              ChatHostPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cerqa_flutter_module.CerqaHostApi.createGroup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val groupNameArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.createGroup(groupNameArg)
              listOf(null)
            } catch (exception: Throwable) {
              ChatHostPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cerqa_flutter_module.CerqaHostApi.deleteGroup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.deleteGroup()
              listOf(null)
            } catch (exception: Throwable) {
              ChatHostPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cerqa_flutter_module.CerqaHostApi.fetchContacts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.fetchContacts{ result: Result<List<Contact>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ChatHostPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ChatHostPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class CerqaFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CerqaFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      ChatHostPigeonCodec()
    }
  }
}
