{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cerqa.flutter.cerqa_flutter_module",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-39d6d6e699e51b2874210e14cddf1a22fb9524b2"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-39d6d6e699e51b2874210e14cddf1a22fb9524b2"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-39d6d6e699e51b2874210e14cddf1a22fb9524b2"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-39d6d6e699e51b2874210e14cddf1a22fb9524b2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3951036,
          "sha512": "657e6af1e4e1f2a3d619d2105004705bf9bd2102ec18cb9a389edb10724595240984e8a7305a1ad86764e397d8fba4e51a674274f47d6b1daa844192044cd4ae",
          "sha256": "ffe074c95fd7bd677d8b22c5b64c6f2988642a0226f6867dd8da5a57d12e96d0",
          "sha1": "91b749e93d17f2bf20b635e5cd3da42f1f4d2363",
          "md5": "7fcb6cfd3bb1707339617cacf0f8b051"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-39d6d6e699e51b2874210e14cddf1a22fb9524b2"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-39d6d6e699e51b2874210e14cddf1a22fb9524b2"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-39d6d6e699e51b2874210e14cddf1a22fb9524b2"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-39d6d6e699e51b2874210e14cddf1a22fb9524b2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3951036,
          "sha512": "657e6af1e4e1f2a3d619d2105004705bf9bd2102ec18cb9a389edb10724595240984e8a7305a1ad86764e397d8fba4e51a674274f47d6b1daa844192044cd4ae",
          "sha256": "ffe074c95fd7bd677d8b22c5b64c6f2988642a0226f6867dd8da5a57d12e96d0",
          "sha1": "91b749e93d17f2bf20b635e5cd3da42f1f4d2363",
          "md5": "7fcb6cfd3bb1707339617cacf0f8b051"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0-sources.jar",
          "url": "flutter_release-1.0-sources.jar",
          "size": 1008,
          "sha512": "6ac6436640930885931051b8fac4aa27f8a847d33e9b96f7e4d8f422aec9ff627670e26ba860e90a5c8c34771ade8d2e0b6a9090b2e46e13082465d6b00ecf72",
          "sha256": "0b75aba57699df30f0bac04dfcc4d000c9b1c96130d09e2346e753cb8f55518e",
          "sha1": "75379ad607250ff70d501d22dd660929347193d5",
          "md5": "a730f69ca4df125c3b9d3a5416b60d6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0-javadoc.jar",
          "url": "flutter_release-1.0-javadoc.jar",
          "size": 261616,
          "sha512": "5b64cd42625ec2c75c9437f18bd3e5c69969556ad3c068ca7bd0242f8c7d23ce6c65d2f8097e005e229d5f241d05929b5c0bf94caa334d45fd2f8e456b2c347f",
          "sha256": "3c5197d7e5a0df80632c6be2dcc3d32fe22a7c0acd3b7be2fa4d01973e5759b0",
          "sha1": "acd5578a961c4af43f01bb0d35115becc8c2d530",
          "md5": "4fdbf6eb2ad0e81958a11cf3a2e9d327"
        }
      ]
    }
  ]
}
